
class Settings:
    HIGHER_GENE = 1
    ITERATIONS = 20
    NUMBER_GENES = 20
    CHROMOSOME_POPULATION = 100
    CROSSOVER_PROB = 0.7
    MUTATION_PROB = 0.001
    MAX_FF = 20
    MAX_GENERATIONS = 50
